### PR TITLE
refactor: integrate scaleway ui website

### PR DESCRIPTION
**Pull request by baptisteArno**
## Summary

Merge https://github.com/scaleway/scaleway-ui-website in this repository

Closes #1797 

## Type

- Refactor

### CODE REVIEW

**Comment by baptisteArno** [comment]
RTR, please ignore the `efactor-integrate-scaleway-ui-website` deployment it won't be there on further pull requests 👍

**Comment by philibea** [comment]
@baptisteArno  missing teardown file for website :)

**Comment by QuiiBz** [comment]
Could we use [PNPM workspaces](https://pnpm.io/workspaces)?

**Comment by baptisteArno** [comment]
> Could we use [PNPM workspaces](https://pnpm.io/workspaces)?

We decided to doing it that way first and if we ever decide to unify other scaleway libs we'll implement a pnpm workspace

**Review by QuiiBz — APPROVED** [review]

**Review by philibea — APPROVED** [review]

**Pull request merged**
