### PR TITLE
docs: revamp website with current guidelines

### PR DESCRIPTION
**Pull request by chambo-e**

### CODE REVIEW

**Comment by philibea** [comment]
@chambo-e 
Tabs doesn't work anymore ?

Capture d’écran 2022-09-20 à 08 59 53

**Comment by philibea** [comment]
Before: 


After:
Capture d’écran 2022-09-20 à 08 59 53

**Review by matthprost — APPROVED** [review]
Love ❤️

**Comment by matthprost** [comment]
> > @chambo-e Tabs doesn't work anymore ?
> > Capture d’écran 2022-09-20 à 08 59 53
> 
> Never has :)

Since refactor of @DorianMaliszewski it is possible that tabs stopped working

**Review by philibea — APPROVED** [review]

**Pull request merged**
