### PR TITLE
fix(tooltip-icon): fixed vertical align

### PR DESCRIPTION
**Pull request by matthprost**
## Type

- Enhancement

#### What is expected?

To be able to change vertical align of tooltip icon.

### CODE REVIEW

**Review by chambo-e — COMMENTED** [review]
Can't we set verticalAlign for all and not allow customisation by props ?

**Review by QuiiBz — APPROVED** [review]

**Comment by matthprost** [comment]
> Can we set verticalAlign for all and not allow customisation by props ?

@chambo-e the purpose of this MR is to be able to set verticalAlign trough props in order to display TooltipIcon differently depending on context.

For example: 

A tooltipIcon showed near a text will have a `vertical-align: text-top` while a tooltipIcon lonely will have `vertical-align: middle`

**Comment by chambo-e** [comment]
> @chambo-e the purpose of this MR is to be able to set verticalAlign trough props in order to display TooltipIcon differently depending on context.
> 
> For example:
> 
> A tooltipIcon showed near a text will have a `vertical-align: text-top` while a tooltipIcon lonely will have `vertical-align: middle`

@matthprost shouldn't this be handled by tooltip instead of changing icon position ? Maybe with placement or gutter ? 
https://reakit.io/docs/tooltip/#usetooltipstate

**Review by DorianMaliszewski — APPROVED** [review]

**Comment by matthprost** [comment]
> > @chambo-e the purpose of this MR is to be able to set verticalAlign trough props in order to display TooltipIcon differently depending on context.
> > For example:
> > A tooltipIcon showed near a text will have a `vertical-align: text-top` while a tooltipIcon lonely will have `vertical-align: middle`
> 
> @matthprost shouldn't this be handled by tooltip instead of changing icon position ? Maybe with placement or gutter ? https://reakit.io/docs/tooltip/#usetooltipstate

There is an issue with tooltipIcon where the box of the tooltip takes big height while it shouldn't I did this PR as quick fix to be able to change the position of the icon.

**Review by chambo-e — APPROVED** [review]

**Pull request merged**
