### PR TITLE
feat: explore loki interactions

### PR DESCRIPTION
**Pull request by vincentaudebert**
## Type

- Enhancement

#### What is expected?

Interactions before loki screenshots

## Relevant logs and/or screenshots

chrome_laptop_Components_Navigation_Menu_Advanced_WIP

### CODE REVIEW

**Comment by vincentaudebert** [comment]
@matthprost @Exayy your thoughts? :/

**Comment by matthprost** [comment]
@vincentaudebert I think its a good solution, seems to work just fine. Do you have any doubts about it ?

**Review by matthprost — APPROVED** [review]

**Comment by vincentaudebert** [comment]
Yes @matthprost few problems spotted:
- I can't seem to be able to have a proper "hover" event. I have to click on the element. It is not ideal. (especially for buttons or links etc.)
- I can't screenshot all the elements at once, for instance on Tooltip when we have multiple tooltips on the same story I can't hover all of them and therefore screenshot would be incomplete? For these cases, maybe we should just screenshot the "default" story... better than nothing :/

**Comment by matthprost** [comment]
@vincentaudebert lets go with this we will improve in another iteration :)

**Pull request merged**
