### PR TITLE
refactor: stories for Badge, Bullet, Borderedbox

### PR DESCRIPTION
**Pull request by vincentaudebert**
## Type

- Documentation

#### What is expected?

Rewrite storybook stories

#### The following changes where made:

(Describe what you did)

1. Check storybook stories for these components

### CODE REVIEW

**Review by matthprost — CHANGES_REQUESTED** [review]
We first need to merge https://github.com/scaleway/scaleway-ui/pull/1942

And you will need to remove `_` in your stories 

EDIT: Please refer to this comment: https://github.com/scaleway/scaleway-ui/pull/1938#pullrequestreview-1139027274

**Comment by baptisteArno** [comment]
And don't forget to rename all the files to `stories.tsx` 👍

**Comment by vincentaudebert** [comment]
RTR @baptisteArno @matthprost

**Review by baptisteArno — APPROVED** [review]
LGTM

**Review by matthprost — APPROVED** [review]

**Pull request merged**
