### PR TITLE
feat: add abbr component

### PR DESCRIPTION
**Pull request by QuiiBz**
## Type

- Feature

#### What is expected?

Add a new `<Abbr />` component

#### The following changes where made:

1. Add the component with snapshot tests and stories

2. Convert some abbreviations in `<Description />` stories with this new component

### CODE REVIEW

**Review by chambo-e — COMMENTED** [review]
Quite confused by this PR, this is a technical encapsulation in a design system

Would this means we need to encapsulate every of our abbreviation on the console ? 

Can't be just add the <abbr> tags in the concerned stories ?

**Comment by QuiiBz** [comment]
> Quite confused by this PR, this means we need to encapsulate every of our abbreviation on the console ?

@iManu asked for this, but not sure if it's a good idea or not

**Comment by chambo-e** [comment]
@QuiiBz I'm all for having this Abbr component in the console codebase, don't really see the point of having it here, to correct the a11y tests we can directly use the native tag in the concerned stories :)

**Review by DorianMaliszewski — APPROVED** [review]

**Comment by matthprost** [comment]
> @QuiiBz I'm all for having this Abbr component in the console codebase, don't really see the point of having it here, to correct the a11y tests we can directly use the native tag in the concerned stories :)

Agree with @chambo-e I think we should directly use native tag or we would have to all tags in Scaleway UI and that's not much the goal 😄

**Comment by chambo-e** [comment]
@QuiiBz yes you can close :)

**Pull request closed without merging**
